//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class AdvantureSlot :  Bright.Config.BeanBase 
{
    public AdvantureSlot(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        weight = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);elements = new System.Collections.Generic.List<gp.E_Element>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { gp.E_Element _e0;  _e0 = (gp.E_Element)_buf.ReadInt(); elements.Add(_e0);}}
        evtType = (gp.E_ADV_EVT_TYPE)_buf.ReadInt();
        evtBody = gp.B_ADV_EVT.DeserializeB_ADV_EVT(_buf);
        PostInit();
    }

    public static AdvantureSlot DeserializeAdvantureSlot(ByteBuf _buf)
    {
        return new gp.AdvantureSlot(_buf);
    }

    /// <summary>
    /// 主键ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 权重
    /// </summary>
    public int weight { get; private set; }
    /// <summary>
    /// 元素组合
    /// </summary>
    public System.Collections.Generic.List<gp.E_Element> elements { get; private set; }
    /// <summary>
    /// 事件类型
    /// </summary>
    public gp.E_ADV_EVT_TYPE evtType { get; private set; }
    /// <summary>
    /// 事件
    /// </summary>
    public gp.B_ADV_EVT evtBody { get; private set; }

    public const int __ID__ = 643347533;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        evtBody?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        evtBody?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "weight:" + weight + ","
        + "elements:" + Bright.Common.StringUtil.CollectionToString(elements) + ","
        + "evtType:" + evtType + ","
        + "evtBody:" + evtBody + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}