//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public abstract partial class B_ADV_EVT :  Bright.Config.BeanBase 
{
    public B_ADV_EVT(ByteBuf _buf) 
    {
        PostInit();
    }

    public static B_ADV_EVT DeserializeB_ADV_EVT(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case gp.B_ADV_EVT_CHEST.__ID__: return new gp.B_ADV_EVT_CHEST(_buf);
            case gp.B_ADV_EVT_BATTLE.__ID__: return new gp.B_ADV_EVT_BATTLE(_buf);
            case gp.B_ADV_EVT_DIALOG.__ID__: return new gp.B_ADV_EVT_DIALOG(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}