//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class B_ADV_EVT_CHEST :  gp.B_ADV_EVT 
{
    public B_ADV_EVT_CHEST(ByteBuf _buf)  : base(_buf) 
    {
        chestModel = _buf.ReadString();
        coin = _buf.ReadInt();
        PostInit();
    }

    public static B_ADV_EVT_CHEST DeserializeB_ADV_EVT_CHEST(ByteBuf _buf)
    {
        return new gp.B_ADV_EVT_CHEST(_buf);
    }

    public string chestModel { get; private set; }
    public int coin { get; private set; }

    public const int __ID__ = 154307703;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "chestModel:" + chestModel + ","
        + "coin:" + coin + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}