//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class B_TF :  Bright.Config.BeanBase 
{
    public B_TF(ByteBuf _buf) 
    {
        camp = (gp.E_BattleCamp)_buf.ReadInt();
        dist = gp.B_TF_Dist.DeserializeB_TF_Dist(_buf);
        attr = gp.B_TF_Attr.DeserializeB_TF_Attr(_buf);
        exSelf = _buf.ReadBool();
        PostInit();
    }

    public static B_TF DeserializeB_TF(ByteBuf _buf)
    {
        return new gp.B_TF(_buf);
    }

    public gp.E_BattleCamp camp { get; private set; }
    public gp.B_TF_Dist dist { get; private set; }
    public gp.B_TF_Attr attr { get; private set; }
    public bool exSelf { get; private set; }

    public const int __ID__ = 174605684;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        dist?.Resolve(_tables);
        attr?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        dist?.TranslateText(translator);
        attr?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "camp:" + camp + ","
        + "dist:" + dist + ","
        + "attr:" + attr + ","
        + "exSelf:" + exSelf + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}