//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class B_TF_Attr :  Bright.Config.BeanBase 
{
    public B_TF_Attr(ByteBuf _buf) 
    {
        isOn = _buf.ReadBool();
        attr = (gp.E_BattleAttribute)_buf.ReadInt();
        value = _buf.ReadInt();
        comp = (gp.E_ValueCompare)_buf.ReadInt();
        PostInit();
    }

    public static B_TF_Attr DeserializeB_TF_Attr(ByteBuf _buf)
    {
        return new gp.B_TF_Attr(_buf);
    }

    public bool isOn { get; private set; }
    public gp.E_BattleAttribute attr { get; private set; }
    public int value { get; private set; }
    public gp.E_ValueCompare comp { get; private set; }

    public const int __ID__ = -1069086212;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "isOn:" + isOn + ","
        + "attr:" + attr + ","
        + "value:" + value + ","
        + "comp:" + comp + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}