//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class B_TS :  Bright.Config.BeanBase 
{
    public B_TS(ByteBuf _buf) 
    {
        method = (gp.E_TS_Method)_buf.ReadInt();
        attr = (gp.E_BattleAttribute)_buf.ReadInt();
        amount = _buf.ReadInt();
        PostInit();
    }

    public static B_TS DeserializeB_TS(ByteBuf _buf)
    {
        return new gp.B_TS(_buf);
    }

    public gp.E_TS_Method method { get; private set; }
    public gp.E_BattleAttribute attr { get; private set; }
    public int amount { get; private set; }

    public const int __ID__ = 174605697;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "method:" + method + ","
        + "attr:" + attr + ","
        + "amount:" + amount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}