//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.gp
{ 
    public enum E_BattleSkillType
    {
        /// <summary>
        /// 普通技能
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 转盘技能
        /// </summary>
        Slot = 1,
    }

} 
