//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.gp
{ 
    [System.Flags]
    public enum E_Element
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 1,
        /// <summary>
        /// 水
        /// </summary>
        Water = 2,
        /// <summary>
        /// 风
        /// </summary>
        Wind = 4,
        /// <summary>
        /// 地
        /// </summary>
        Earth = 8,
        /// <summary>
        /// 光
        /// </summary>
        Light = 16,
        /// <summary>
        /// 暗
        /// </summary>
        Dark = 32,
    }

} 
