//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.gp
{ 
    public enum E_TS_Method
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 1,
        /// <summary>
        /// 随机
        /// </summary>
        Random = 2,
        /// <summary>
        /// 最近
        /// </summary>
        Nearest = 3,
        /// <summary>
        /// 最远
        /// </summary>
        Farest = 4,
        /// <summary>
        /// 对位
        /// </summary>
        Match = 5,
        /// <summary>
        /// 全体
        /// </summary>
        All = 6,
        /// <summary>
        /// 自己
        /// </summary>
        Self = 7,
        /// <summary>
        /// 属性最低
        /// </summary>
        AttrLowest = 8,
        /// <summary>
        /// 属性最高
        /// </summary>
        AttrHighest = 9,
    }

} 
