//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.gp
{ 
    public enum E_ValueCompare
    {
        /// <summary>
        /// 等于
        /// </summary>
        Equal = 0,
        /// <summary>
        /// 不等于
        /// </summary>
        NEqual = 1,
        /// <summary>
        /// 大于
        /// </summary>
        Greater = 2,
        /// <summary>
        /// 大于等于
        /// </summary>
        GEqual = 3,
        /// <summary>
        /// 小于
        /// </summary>
        Less = 4,
        /// <summary>
        /// 小于等于
        /// </summary>
        LEqual = 5,
    }

} 
