//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class GlobalDefines :  Bright.Config.BeanBase 
{
    public GlobalDefines(ByteBuf _buf) 
    {
        GlobalA = _buf.ReadInt();
        GlobalB = _buf.ReadString();
        GlobalC = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);GlobalD = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); GlobalD.Add(_e0);}}
        PostInit();
    }

    public static GlobalDefines DeserializeGlobalDefines(ByteBuf _buf)
    {
        return new gp.GlobalDefines(_buf);
    }

    public int GlobalA { get; private set; }
    public string GlobalB { get; private set; }
    public float GlobalC { get; private set; }
    public System.Collections.Generic.List<string> GlobalD { get; private set; }

    public const int __ID__ = -531279728;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GlobalA:" + GlobalA + ","
        + "GlobalB:" + GlobalB + ","
        + "GlobalC:" + GlobalC + ","
        + "GlobalD:" + Bright.Common.StringUtil.CollectionToString(GlobalD) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}