//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.gp
{ 
    public enum HeroClass
    {
        /// <summary>
        /// 普通
        /// </summary>
        NORMAL = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        RARE = 2,
        /// <summary>
        /// 史诗
        /// </summary>
        EPIC = 3,
        /// <summary>
        /// 传说
        /// </summary>
        LEGEND = 4,
    }

} 
