//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class SkillLevel :  Bright.Config.BeanBase 
{
    public SkillLevel(ByteBuf _buf) 
    {
        SkillId = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);LevelInfos = new System.Collections.Generic.List<gp.SkillLevelInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { gp.SkillLevelInfo _e0;  _e0 = gp.SkillLevelInfo.DeserializeSkillLevelInfo(_buf); LevelInfos.Add(_e0);}}
        PostInit();
    }

    public static SkillLevel DeserializeSkillLevel(ByteBuf _buf)
    {
        return new gp.SkillLevel(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public int SkillId { get; private set; }
    public System.Collections.Generic.List<gp.SkillLevelInfo> LevelInfos { get; private set; }

    public const int __ID__ = -350708232;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in LevelInfos) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in LevelInfos) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "SkillId:" + SkillId + ","
        + "LevelInfos:" + Bright.Common.StringUtil.CollectionToString(LevelInfos) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}