//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
public sealed partial class Skill :  Bright.Config.BeanBase 
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        IsUlt = _buf.ReadBool();
        PostInit();
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new gp.Skill(_buf);
    }

    /// <summary>
    /// 主键ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 是大招
    /// </summary>
    public bool IsUlt { get; private set; }

    public const int __ID__ = 1133887724;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "IsUlt:" + IsUlt + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}