//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
   
public partial class TblActor
{
    private readonly Dictionary<int, gp.Actor> _dataMap;
    private readonly List<gp.Actor> _dataList;
    
    public TblActor(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, gp.Actor>();
        _dataList = new List<gp.Actor>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            gp.Actor _v;
            _v = gp.Actor.DeserializeActor(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, gp.Actor> DataMap => _dataMap;
    public List<gp.Actor> DataList => _dataList;

    public gp.Actor GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public gp.Actor Get(int key) => _dataMap[key];
    public gp.Actor this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}