//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
   
public partial class TblGlobalDefines
{

     private readonly gp.GlobalDefines _data;

    public TblGlobalDefines(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = gp.GlobalDefines.DeserializeGlobalDefines(_buf);
        PostInit();
    }


     public int GlobalA => _data.GlobalA;
     public string GlobalB => _data.GlobalB;
     public float GlobalC => _data.GlobalC;
     public System.Collections.Generic.List<string> GlobalD => _data.GlobalD;

    public void Resolve(Dictionary<string, object> _tables)
    {
        _data.Resolve(_tables);
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        _data.TranslateText(translator);
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}