//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.gp
{
   
public partial class TblSkillLevel
{
    private readonly Dictionary<int, gp.SkillLevel> _dataMap;
    private readonly List<gp.SkillLevel> _dataList;
    
    public TblSkillLevel(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, gp.SkillLevel>();
        _dataList = new List<gp.SkillLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            gp.SkillLevel _v;
            _v = gp.SkillLevel.DeserializeSkillLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SkillId, _v);
        }
        PostInit();
    }

    public Dictionary<int, gp.SkillLevel> DataMap => _dataMap;
    public List<gp.SkillLevel> DataList => _dataList;

    public gp.SkillLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public gp.SkillLevel Get(int key) => _dataMap[key];
    public gp.SkillLevel this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}