//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public gp.TblGlobalDefines TblGlobalDefines {get; }
    public gp.TblActor TblActor {get; }
    public gp.TblSkill TblSkill {get; }
    public gp.TblSkillLevel TblSkillLevel {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TblGlobalDefines = new gp.TblGlobalDefines(loader("gp_tblglobaldefines")); 
        tables.Add("gp.TblGlobalDefines", TblGlobalDefines);
        TblActor = new gp.TblActor(loader("gp_tblactor")); 
        tables.Add("gp.TblActor", TblActor);
        TblSkill = new gp.TblSkill(loader("gp_tblskill")); 
        tables.Add("gp.TblSkill", TblSkill);
        TblSkillLevel = new gp.TblSkillLevel(loader("gp_tblskilllevel")); 
        tables.Add("gp.TblSkillLevel", TblSkillLevel);

        PostInit();
        TblGlobalDefines.Resolve(tables); 
        TblActor.Resolve(tables); 
        TblSkill.Resolve(tables); 
        TblSkillLevel.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TblGlobalDefines.TranslateText(translator); 
        TblActor.TranslateText(translator); 
        TblSkill.TranslateText(translator); 
        TblSkillLevel.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}